http://localhost:3005/users

###

POST http://localhost:3005/users HTTP/1.1
Content-Type: application/json

{
  "username": "newUser",
  "bio": "Im new."
}

###

PUT http://localhost:3005/users/1 HTTP/1.1
Content-Type: application/json

{
  "username": "mom13",
  "bio": "Im mom12."
}

###

DELETE http://localhost:3005/users/4 HTTP/1.1
Content-Type: application/json